In [1]:
import pandas as pd
import numpy as np

Reading Money Supply

In [2]:
money_supply = pd.read_excel('Money Supply 1960-2024.xlsx')

In [3]:
money_supply.shape

(409, 21)

In [4]:
money_supply.head(3)

,Year,Month,Narrow Money,Money Supply M3,Net Foreign Assets,Net Domestic Credit,Credit to Government,Credit to Private Sector,Base Money,Currency in Circulation,...,Currency Outside Banks,Demand Deposits,Quasi Money,Net Domestic Assets,Credit To GovernmentFed,Mirror Accounts,Other Assets Net,Money Supply M2,CBN Bills,Special Intervention Reserves
0,2024,1,31555882.24,94614600.44,29739769.64,9.999764e+07,23518053.15,76479585.58,24164031.04,3650500.20,...,3281198.20,28274684.04,62216126.61,64874830.79,0.0,0.0,6732309.44,93772008.85,842591.59,433229.15
1,2024,2,30277249.26,95557263.40,7408009.72,1.147889e+08,33925848.79,80863019.16,21230656.70,3693573.23,...,3411735.44,26865513.82,63691242.70,88149253.67,0.0,0.0,13319068.99,93968491.96,1588771.44,433229.15
2,2024,3,32489908.18,92343286.66,35785309.22,9.080104e+07,19589769.97,71211271.38,23384818.66,3869330.26,...,3627522.07,28862386.11,59842712.03,56557977.44,0.0,0.0,9975496.63,92332620.21,10666.45,433229.15

In [5]:
money_supply.isna().sum()

Year                               0
Month                              0
Narrow Money                       0
Money Supply M3                  236
Net Foreign Assets                 0
Net Domestic Credit                0
Credit to Government               0
Credit to Private Sector           0
Base Money                         0
Currency in Circulation            0
Bank Reserves                      0
Currency Outside Banks             0
Demand Deposits                    0
Quasi Money                        0
Net Domestic Assets                0
Credit To GovernmentFed          236
Mirror Accounts                  236
Other Assets Net                   0
Money Supply M2                    0
CBN Bills                        236
Special Intervention Reserves    275
dtype: int64

In [6]:
money_supply['Money Supply M3'].fillna(value=money_supply['Money Supply M3'].mean(), inplace=True)

money_supply['Credit To GovernmentFed'].fillna(value=money_supply['Credit To GovernmentFed'].mean() , inplace=True)

money_supply['Mirror Accounts'].fillna(value=money_supply['Mirror Accounts'].mean(), inplace=True)

money_supply['CBN Bills'].fillna(value=money_supply['CBN Bills'].mean(), inplace=True)

money_supply['Special Intervention Reserves'].fillna(value=money_supply['Special Intervention Reserves'].mean(), inplace=True)

In [7]:
money_supply.isna().sum()

Year                             0
Month                            0
Narrow Money                     0
Money Supply M3                  0
Net Foreign Assets               0
Net Domestic Credit              0
Credit to Government             0
Credit to Private Sector         0
Base Money                       0
Currency in Circulation          0
Bank Reserves                    0
Currency Outside Banks           0
Demand Deposits                  0
Quasi Money                      0
Net Domestic Assets              0
Credit To GovernmentFed          0
Mirror Accounts                  0
Other Assets Net                 0
Money Supply M2                  0
CBN Bills                        0
Special Intervention Reserves    0
dtype: int64

A discrepency has been identified in the Months column of given data. For rowID 375 onward, the Month value is set to year value. The is needed to be correct for future analysis.

In [9]:
money_supply.tail(35)

,Year,Month,Narrow Money,Money Supply M3,Net Foreign Assets,Net Domestic Credit,Credit to Government,Credit to Private Sector,Base Money,Currency in Circulation,...,Currency Outside Banks,Demand Deposits,Quasi Money,Net Domestic Assets,Credit To GovernmentFed,Mirror Accounts,Other Assets Net,Money Supply M2,CBN Bills,Special Intervention Reserves
374,1993,6,91429.18,3.036898e+07,64137.99,205474.23,71209.25,134264.98,93221.16,47850.76,...,44616.46,46812.72,68022.20,95313.39,2.681923e+06,-1.618844e+06,-110160.84,159451.38,2.447132e+06,258214.992388
375,1993,7,96050.64,3.036898e+07,65430.84,220585.03,72739.94,147845.09,92635.94,50241.24,...,47301.14,48749.50,70886.20,101506.00,2.681923e+06,-1.618844e+06,-119079.03,166936.84,2.447132e+06,258214.992388
376,1992,1992,75970.27,3.036898e+07,35778.25,171071.02,91112.10,79958.92,71865.93,39725.03,...,36755.53,39214.74,53115.20,93307.19,2.681923e+06,-1.618844e+06,-77763.84,129085.47,2.447132e+06,258214.992388
377,1991,1991,50071.70,3.036898e+07,56045.30,81705.00,39626.00,42079.00,29871.70,25331.20,...,23120.60,26951.10,37428.10,31454.50,2.681923e+06,-1.618844e+06,-50250.50,87499.80,2.447132e+06,258214.992388
378,1990,1990,39156.20,3.036898e+07,43909.90,58209.30,22772.70,35436.60,18341.00,16212.50,...,14951.10,24205.10,29506.30,24752.60,2.681923e+06,-1.618844e+06,-33456.70,68662.50,2.447132e+06,258214.992388
379,1989,1989,26268.80,3.036898e+07,22524.30,37004.20,7360.30,29643.90,11840.40,10722.40,...,9760.60,16508.20,20786.20,24530.70,2.681923e+06,-1.618844e+06,-12473.50,47055.00,2.447132e+06,258214.992388
380,1988,1988,22232.10,3.036898e+07,9492.40,54813.10,29340.60,25472.50,11740.60,10210.50,...,9413.60,12818.50,23214.80,35954.50,2.681923e+06,-1.618844e+06,-18858.60,45446.90,2.447132e+06,258214.992388
381,1987,1987,15195.70,3.036898e+07,3700.50,44140.00,22247.50,21892.50,8491.80,6854.90,...,6298.60,8897.10,18471.70,29966.90,2.681923e+06,-1.618844e+06,-14173.10,33667.40,2.447132e+06,258214.992388
382,1986,1986,13560.40,3.036898e+07,5367.80,37850.50,19550.60,18299.90,6666.40,5696.30,...,5177.90,8382.50,13829.40,22022.00,2.681923e+06,-1.618844e+06,-15828.50,27389.80,2.447132e+06,258214.992388
383,1985,1985,13878.00,3.036898e+07,1418.40,34462.60,20323.60,14139.00,5715.10,5375.00,...,4909.90,8968.10,12399.60,24859.20,2.681923e+06,-1.618844e+06,-9603.40,26277.60,2.447132e+06,258214.992388
384,1984,1984,12497.10,3.036898e+07,1110.70,32020.60,19125.30,12895.30,5915.60,5347.20,...,4883.50,7613.60,10872.90,22259.30,2.681923e+06,-1.618844e+06,-9761.30,23370.00,2.447132e+06,258214.992388
385,1983,1983,11517.80,3.036898e+07,501.40,28687.90,16450.10,12237.80,6109.50,5299.30,...,4842.80,6675.00,9361.30,20377.70,2.681923e+06,-1.618844e+06,-8310.20,20879.10,2.447132e+06,258214.992388
386,1982,1982,10291.80,3.036898e+07,888.10,22272.00,10660.60,11611.40,5784.50,4728.90,...,4222.50,6069.30,7801.80,17205.50,2.681923e+06,-1.618844e+06,-5066.50,18093.60,2.447132e+06,258214.992388
387,1981,1981,9915.30,3.036898e+07,2585.00,16203.40,6532.90,9670.50,5026.10,4347.70,...,3861.90,6053.40,6246.40,13576.70,2.681923e+06,-1.618844e+06,-2626.70,16161.70,2.447132e+06,258214.992388
388,1980,1980,9650.70,3.036898e+07,5622.00,11025.60,3567.80,7457.80,4797.50,3589.50,...,3185.90,6464.80,5449.30,9478.00,2.681923e+06,-1.618844e+06,-1547.60,15100.00,2.447132e+06,258214.992388
389,1979,1979,6351.50,3.036898e+07,3232.20,8765.20,3365.60,5399.60,3083.40,2703.40,...,2350.80,4000.70,3873.10,6992.40,2.681923e+06,-1.618844e+06,-1772.80,10224.60,2.447132e+06,258214.992388
390,1978,1978,5260.70,3.036898e+07,1192.90,7017.40,2504.40,4513.00,2898.60,2381.70,...,2157.20,3103.50,2724.70,6792.50,2.681923e+06,-1.618844e+06,-224.90,7985.40,2.447132e+06,258214.992388
391,1977,1977,5557.80,3.036898e+07,2722.30,5162.20,1353.80,3808.40,2792.60,2162.60,...,1940.80,3617.00,2341.00,5176.50,2.681923e+06,-1.618844e+06,14.30,7898.80,2.447132e+06,258214.992388
392,1976,1976,3864.10,3.036898e+07,3170.20,3309.90,845.50,2464.40,2445.20,1540.00,...,1351.20,2512.90,2041.00,2734.90,2.681923e+06,-1.618844e+06,-575.00,5905.10,2.447132e+06,258214.992388
393,1975,1975,2605.40,3.036898e+07,3533.20,1217.90,-453.90,1671.80,1859.40,1155.50,...,1030.70,1574.70,1635.80,708.00,2.681923e+06,-1.618844e+06,-509.90,4241.20,2.447132e+06,258214.992388
394,1974,1974,1357.20,3.036898e+07,3492.50,-310.30,-1277.00,966.70,744.10,638.70,...,569.90,787.30,995.10,-1140.20,2.681923e+06,-1.618844e+06,-829.90,2352.30,2.447132e+06,258214.992388
395,1973,1973,925.80,3.036898e+07,403.00,1316.90,563.30,753.60,501.70,486.30,...,435.90,489.90,596.70,1119.50,2.681923e+06,-1.618844e+06,-197.40,1522.50,2.447132e+06,258214.992388
396,1972,1972,747.40,3.036898e+07,229.50,1235.00,606.30,628.70,428.90,414.00,...,385.20,362.20,467.50,985.40,2.681923e+06,-1.618844e+06,-249.60,1214.90,2.447132e+06,258214.992388
397,1971,1971,670.00,3.036898e+07,267.50,1099.20,597.20,502.00,392.80,386.40,...,354.40,315.60,371.80,774.30,2.681923e+06,-1.618844e+06,-324.90,1041.80,2.447132e+06,258214.992388
398,1970,1970,641.50,3.036898e+07,128.15,1120.30,768.60,351.70,388.90,370.40,...,342.40,299.10,336.70,850.00,2.681923e+06,-1.618844e+06,-270.30,978.20,2.447132e+06,258214.992388
399,1969,1969,444.99,3.036898e+07,87.80,761.94,512.19,249.74,277.91,273.23,...,252.71,192.28,215.41,572.59,2.681923e+06,-1.618844e+06,-189.34,660.40,2.447132e+06,258214.992388
400,1968,1968,331.76,3.036898e+07,64.16,574.25,351.41,222.84,205.67,202.16,...,183.10,148.67,183.55,451.16,2.681923e+06,-1.618844e+06,-123.09,515.31,2.447132e+06,258214.992388
401,1967,1967,320.09,3.036898e+07,46.72,432.86,191.35,241.51,226.73,220.95,...,207.42,112.67,131.24,404.61,2.681923e+06,-1.618844e+06,-28.25,451.34,2.447132e+06,258214.992388
402,1966,1966,355.62,3.036898e+07,126.49,381.74,136.18,245.56,239.87,236.51,...,217.17,138.45,162.52,391.65,2.681923e+06,-1.618844e+06,9.91,518.14,2.447132e+06,258214.992388
403,1965,1965,326.36,3.036898e+07,154.60,313.09,80.48,232.61,220.48,217.89,...,200.94,125.41,141.02,312.78,2.681923e+06,-1.618844e+06,-0.31,467.37,2.447132e+06,258214.992388
404,1964,1964,316.06,3.036898e+07,124.89,306.08,83.13,222.96,217.02,214.71,...,197.89,118.17,114.43,305.59,2.681923e+06,-1.618844e+06,-0.49,430.49,2.447132e+06,258214.992388
405,1963,1963,267.55,3.036898e+07,133.45,237.57,67.07,170.50,185.46,183.30,...,168.98,98.57,94.27,228.37,2.681923e+06,-1.618844e+06,-9.20,361.82,2.447132e+06,258214.992388
406,1962,1962,242.14,3.036898e+07,156.34,187.00,38.22,148.78,177.51,174.66,...,149.96,92.18,83.29,169.09,2.681923e+06,-1.618844e+06,-17.91,325.43,2.447132e+06,258214.992388
407,1961,1961,222.32,3.036898e+07,163.63,143.77,26.64,117.13,166.96,160.19,...,138.20,84.12,70.51,129.20,2.681923e+06,-1.618844e+06,-14.56,292.83,2.447132e+06,258214.992388
408,1960,1960,217.61,3.036898e+07,150.28,117.63,8.30,109.33,157.05,154.15,...,135.32,82.28,54.79,122.12,2.681923e+06,-1.618844e+06,4.49,272.40,2.447132e+06,258214.992388

The identified problem in given data is resolved by using Group by function which is used to group data based on year and computes mean for months value ( if available)

In [10]:
money_supply = money_supply.groupby(['Year'], as_index=True).mean().round(2)

The month column has beed dropped as we longer need it

In [11]:
money_supply.drop(columns='Month', inplace=True)
money_supply.head(5)

,Narrow Money,Money Supply M3,Net Foreign Assets,Net Domestic Credit,Credit to Government,Credit to Private Sector,Base Money,Currency in Circulation,Bank Reserves,Currency Outside Banks,Demand Deposits,Quasi Money,Net Domestic Assets,Credit To GovernmentFed,Mirror Accounts,Other Assets Net,Money Supply M2,CBN Bills,Special Intervention Reserves
Year,,,,,,,,,,,,,,,,,,,
1960,217.61,30368977.77,150.28,117.63,8.30,109.33,157.05,154.15,2.90,135.32,82.28,54.79,122.12,2681922.73,-1618844.16,4.49,272.40,2447132.17,258214.99
1961,222.32,30368977.77,163.63,143.77,26.64,117.13,166.96,160.19,6.76,138.20,84.12,70.51,129.20,2681922.73,-1618844.16,-14.56,292.83,2447132.17,258214.99
1962,242.14,30368977.77,156.34,187.00,38.22,148.78,177.51,174.66,2.85,149.96,92.18,83.29,169.09,2681922.73,-1618844.16,-17.91,325.43,2447132.17,258214.99
1963,267.55,30368977.77,133.45,237.57,67.07,170.50,185.46,183.30,2.16,168.98,98.57,94.27,228.37,2681922.73,-1618844.16,-9.20,361.82,2447132.17,258214.99
1964,316.06,30368977.77,124.89,306.08,83.13,222.96,217.02,214.71,2.31,197.89,118.17,114.43,305.59,2681922.73,-1618844.16,-0.49,430.49,2447132.17,258214.99

In [13]:
money_supply.duplicated().unique()

array([False])

In [14]:
money_supply.to_csv('MoneySupply_1960-2024_Yearly.csv')

Real Estate Data

In [15]:
real_estate = pd.read_csv('Real Estate Annually.csv')

In [16]:
real_estate

,Mnemonic,Parent Mnemonic,Databank,Data Family,Data Source,Units of Measure,First Observation,Frequency,Name of Series,1981,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,NGRPA19,NGRPA12,REL,National accounts,National Bureau of Statistics,millions of naira,1981,A,3.7 Real estate,1063959.81,...,5155727.95,5264695.89,4903604.64,4694391.27,4471861.75,4366350.6,3963589.18,4053083.2,4213070.41,4283647.4

In [17]:
real_estate = real_estate.transpose()
re = pd.DataFrame(real_estate.iloc[9:,:])
re.rename(columns={0:'Real Estate (millions of naira)'},inplace=True)

In [28]:
re.head(3)

     Real Estate (millions of naira)
1981                      1063959.81
1982                      1074049.33
1983                      1086703.98

In [24]:
re.shape

(43, 1)

In [18]:
re.isna().sum()

Real Estate (millions of naira)    0
dtype: int64

In [20]:
re.duplicated().unique()

array([False])

In [21]:
re.to_csv('RealEstate_1981-2023_Yearly.csv')

Major Imports

In [22]:
major_imports = pd.read_excel('major imports 1960-2006.xlsx')

In [23]:
major_imports.head(3)

,Year,Food & Live Animal,Beverages & Tobacco,Crude Mineral Inedible,Mineral Fuels,Animals & Vegetable Oils & Fats,Chemicals,Manufactured Goods,Machinery & Transport Equipment,Miscellaneous Manufactured Goods,Miscellaneous Transactions,Total
0,1960,47.822,12.304,4.292,22.660,0.130,24.464,162.268,103.280,47.826,6.736,431.782
1,1961,45.448,12.220,4.908,26.760,0.126,25.192,175.034,101.008,47.500,6.842,445.038
2,1962,46.986,9.538,4.818,28.148,0.168,24.664,146.130,96.532,43.306,6.144,406.434

In [25]:
major_imports.shape

(50, 12)

In [26]:
major_imports.isna().sum()

Year                                0
Food & Live Animal                  0
Beverages & Tobacco                 0
 Crude Mineral Inedible             0
Mineral Fuels                       0
Animals & Vegetable Oils & Fats     0
Chemicals                           0
Manufactured Goods                  0
Machinery & Transport Equipment     0
Miscellaneous Manufactured Goods    0
 Miscellaneous Transactions         0
Total                               0
dtype: int64

In [27]:
major_imports.duplicated().unique()

array([False])

In [30]:
major_imports = major_imports.set_index('Year')
major_imports.head(3)

,Food & Live Animal,Beverages & Tobacco,Crude Mineral Inedible,Mineral Fuels,Animals & Vegetable Oils & Fats,Chemicals,Manufactured Goods,Machinery & Transport Equipment,Miscellaneous Manufactured Goods,Miscellaneous Transactions,Total
Year,,,,,,,,,,,
1960,47.822,12.304,4.292,22.660,0.130,24.464,162.268,103.280,47.826,6.736,431.782
1961,45.448,12.220,4.908,26.760,0.126,25.192,175.034,101.008,47.500,6.842,445.038
1962,46.986,9.538,4.818,28.148,0.168,24.664,146.130,96.532,43.306,6.144,406.434

In [31]:
major_imports.to_csv('MajorImports_1960-2006_Yearly.csv')